### PR TITLE
Added support for Udemy Business

### PR DESCRIPTION
**Pull request by miguelduarte42**
Udemy Business requires some URL changes for the course listing and downloading to be successful. This PR includes two new input elements on the login form that then are used to adjust the URL of the requests.

For instance, if your Udemy Business account is located at https://coolcompany.udemy.com, you just need to tick the checkbox for "Udemy Business?" and then type "coolcompany" in the new text field that appears.

### CODE REVIEW

**Comment by FaisalUmair** [comment]
Hello. Thank you so much for your contribution to this project. 

Since I don't have any Udemy business account. I cannot test the integration personally. But you must have tested it, so I assume its working fine already. Also someone here was asking for this, I will link this PR to him so that he can also confirm it. As for the design, I will make some little changes so that it matches the overall UI. Once everything is done, I will merge this PR and release a new version of Udeler.

**Comment by miguelduarte42** [comment]
Hi! Yes, it worked great with my account. The UI I added can certainly be improved :)

**Comment by mdklab** [comment]
That change works perfect for my business account.
Thanks a lot Miguel!

**Comment by FaisalUmair** [comment]
Hi @mdklab , Thanks for confirming. And @miguelduarte42 I am working on a new update, I will just modify the design a little and then merge this. I will make sure it is available to everyone in next release.

Thank you :)

**Comment by akhilpadgilwar** [comment]
> That change works perfect for my business account.
> Thanks a lot Miguel!

can you help me with business account? mine is not working.

**Pull request merged**
