### PR TITLE
Added brazilian portuguese language

### PR DESCRIPTION
**Pull request by williamokano**
Please add this brazilian portuguese translation. I'm pt_BR native, so, no translator used.

Notice that instead of using `por` as asked for the language (ISO 639-2 Code) I used pt_BR. I know that is not on guideline, it should be `por` but, there are some variations of portuguese, so it's quite common using pt (or por) as portuguese from Portugal and pr_BR for Brazilian Portuguese.

Some slightly diffences can be found as, in pt, file is `ficheiro` while in Brasil file is `arquivo` because in Brasil `ficheiro` is a binder.

If even after that it still not acceptable, I can change the code for `por`, but it could generate some confusion if in the future someone try to add the portuguese from portugal to the Udeler.

### CODE REVIEW

**Comment by FaisalUmair** [comment]
Since you are Brazilian Portuguese native, you obviously know what you are doing. I will merge the pull pull request. But let me know if changing the name of the language from Português to Brazilian Português or Português (Brazilian) is a good idea?

**Comment by williamokano** [comment]
@FaisalUmair Actually it is a very good idea. The *right* name should be `Português (Brasil)` but the app wasn't recognizing the language. Since I had no time to look for a fix, I left it just portuguese.

I think that could be a bug. Try to add a language to meta with separated words, like `Português - Brasil` (in the settings this would be the best option). That was my first try.

The listing shows the language but when I select and restart the changed don't apply.

**Comment by FaisalUmair** [comment]
No problem Sir, I will change it myself and will make it available in the next release.

Thank you so much for your contribution.

**Comment by williamokano** [comment]
OK. Thank you for creating this. You're awesome 👍

**Comment by tofanelli** [comment]
@FaisalUmair .... or you can just name it as - Portugues (BR) - which stands for BRazil, and when it comes to Portuguese from Portugal, you can name it as - Portuguese (PT) ... it will work in the same way =)

**Comment by williamokano** [comment]
@tofanelli it will work, but the problem is that, at the moment I wrote the PR, the languages name couldn't contain spaces, that's why I said that I had no time for a fix and "just" left as `Português`, without country.

I think that if the problem is already fixed, `Português (BR)` and `Português (PT)` is indeed the best naming one could choose.

**Comment by FaisalUmair** [comment]
@tofanelli , @williamokano  I think I am  not the right person to ask this question. But if there are two versions of Portuguese language then I think we should separate them accordingly. But as of now we only have Brazilian Portuguese added  so I think it is okay to  name the language just Portuguese. 

But I will see whats wrong with the space issue here, if fixed, I will rename it to Portuguese (BR). Would that be alright?

**Comment by williamokano** [comment]
Yes, Will be :)

Em dom, 11 de mar de 2018 02:54, Faisal Umair <notifications@github.com>
escreveu:

**Comment by tofanelli** [comment]
@FaisalUmair .... yup... it will =)

**Pull request merged**
