### PR TITLE
Update it.json

### PR DESCRIPTION
**Pull request by m4dbra1n**
A little revision + request to give the column of Courses and Settings a little more width to not break the word :)

### CODE REVIEW

**Comment by FaisalUmair** [comment]
Hi, Thanks for taking your time to review the file. 

I see that you have edited two values Download Settings and Application Settings. But the translated word skips the "Settings" part of the word. I guess you have tried to make it little clean and obvious to the user that they are already in the Settings tab. But since the files are meant to translate exactly what is written already in English so that we can maintain uniform design across different translations of the application. We cannot skip the "Settings" word for just one language only, for example the Spanish language and English language both contain the "Settings" word, so changing it for only one language would not be good in my opinion. 

And for the word break on the menu items that do not fit the container, we can increase the width but for the english part it will take more width than it should and since we are not sure if other languages will require us to increase the width more, therefore I think it is best to break the word so that the sidebar takes equal width for all languages.

Please let me know your thoughts. 

Thanks

**Comment by m4dbra1n** [comment]
Oh OK, my intent was only to not have a double repetition, since, as you understood, since the user in already in the Settings page, that would be only a repetition. Nevermind, o understand that you want the translation to adhere the best they can to be omogeneous between them ;)

I too don't know if I'm other languages they need more space as in Italian, I think you'll see that in the future, if more translators will join :)

**Comment by FaisalUmair** [comment]
Yes Sir, I guessed why you would want to remove the "Settings" word and logically you are correct. But since we have the "Settings" included in the English and Spanish translation removing it in Italian would force us to remove it in other languages also if we want the design to be uniform across different translations of the app. But we will see how that goes in future, may be we will remove it in English then the other languages will follow. 

And yes for the word break on menu names, we both agree that there is no certainty about the length of words in other translations. And I believe it is always a good practice to keep the size of menu fixed regardless of the length of its content and hence the word-break comes in place.  

Let me know if we are good about this for now, so that I can close this PR?

**Comment by m4dbra1n** [comment]
Totally agree ;) you can close it with no problem :+1:

**Pull request closed without merging**
