### PR TITLE
Added Video Numbering Schemes

### PR DESCRIPTION
**Pull request by blackpanther989**
[] Added Video numbering schemes
( Raw = original method )
( Padded = original method with padding IE 001. )
( Consecutive = Padded consecutive numbering. )

### CODE REVIEW

**Comment by FaisalUmair** [comment]
Thank you so much for adding this. I had plans to add this feature but didn't got time. You got this covered :)

I haven't tested it yet, but I think you must have tested it before submitting.

I am working on a new release, I will test the naming scheme anyway and make it available in the next release.

**Comment by blackpanther989** [comment]
Hi Faisal,

I only set it up to rename the videos I Didn't want it to rename the attachments. I only wanted it to rename the videos. I can look into having it rename the attachments as well but it doesn't fit with the consecutive naming.

**Comment by FaisalUmair** [comment]
@blackpanther989 the numbering scheme should be constant for all types of files.  

And what's up with removing the subdomain variable from the api calls?

And if possible please fork the latest version and make changes to it as I have already committed some changes to the same file and your changes are conflicting with mine.

**Comment by blackpanther989** [comment]
closing this pull request I have deleted the original fork I had and re-forked it.

**Pull request closed without merging**
